server:
  servlet:
    context-path: /club-evidence

spring:
  datasource:
    url: jdbc:h2:mem:ear
    driver-class-name: org.h2.Driver
    username: e
    password: 69
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
logging:
  level:
    org.springframework.security.web: DEBUG